--- #YAML:1.0
name:               Coro-Amazon-SimpleDB
version:            0.03
abstract:           Use C<Amazon::SimpleDB::Client> to do asynchronous requests
author:
    - Dave Trischuk <dtrischuk@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Amazon::SimpleDB::Client:  0
    AnyEvent:             0
    AnyEvent::HTTP:       0
    Carp:                 0
    common::sense:        0
    Coro:                 0
    Coro::AnyEvent:       0
    EV:                   0
    HTTP::Request:        0
    HTTP::Response:       0
    List::Util:           0
    Moose:                0
    Scalar::Util:         0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
